site_name: WebSite X5 Developer's Guide
site_author: Incomedia Srl
site_url: http://devguide.websitex5.com
repo_url: https://github.com/WebSiteX5/wsx5-developers-guide
copyright: © 2021 - Incomedia Srl
use_directory_urls: false
theme: readthedocs
strict: false
extra_javascript: [jslibs/css_classes.js]
extra_css: [css/cssfix.css]
markdown_extensions: [nl2br]
site_favicon: favicon.ico
pages:
  - 'Home': 'index.md'
  - Optional Objects:
    - 'Introduction': 'optional-objects/introduction.md'
    - 'Getting Started': 'optional-objects/getting-started.md'
    - 'Optional Objects structure': 'optional-objects/conventions-structure.md'
    - 'Manifest XML': 'optional-objects/manifest-xml.md'
    - 'User input fields': 'optional-objects/user-input-fields.md'
    - 'Localizations': 'optional-objects/localizations-xml.md'
    - 'Hacking the default behavior': 'optional-objects/hooks.md'
    - 'WSX5 Script': 'optional-objects/wsx5-script.md'
    - 'Tips': 'optional-objects/tips.md'
    - 'Example Objects': 'optional-objects/examples.md'
    - 'Dynamically Update Fields Values': 'optional-objects/dynamic-update-fields.md'
  - X5 Engine JavaScript API:
    - 'Introduction': 'generic-javascript-api/introduction.md'
    - 'Boot Class': 'generic-javascript-api/boot.md'
    - 'Showbox Class': 'generic-javascript-api/showbox.md'
    - 'Tooltip Class': 'generic-javascript-api/tip.md'
    - 'Localizations Class': 'generic-javascript-api/l10n.md'
    - 'Responsive Class': 'generic-javascript-api/responsive.md'
    - 'Responsive Events': 'generic-javascript-api/responsive-events.md'
    - 'Cookie Law Script': 'generic-javascript-api/cookielaw-script.md'
  - Ecommerce JavaScript API:
    - 'Introduction': 'ecommerce-javascript-api/introduction.md'
    - 'E-Commerce Class': 'ecommerce-javascript-api/ecommerce-class.md'
    - 'Product Class': 'ecommerce-javascript-api/product-class.md'
    - 'Payment Class': 'ecommerce-javascript-api/payment-class.md'
    - 'Shipping Class': 'ecommerce-javascript-api/shipping-class.md'
    - 'User Interface': 'ecommerce-javascript-api/ui.md'
  - X5 Engine PHP API:
    - 'Introduction': 'php-api/introduction.md'
    - 'Global Functions': 'php-api/global-functions.md'
    - 'Comment Class': 'php-api/comment-class.md'
    - 'Database Class': 'php-api/database-class.md'
    - 'Private Area Class': 'php-api/privatearea-class.md'
    - 'Topic Class': 'php-api/topic-class.md'
